// The tab icons and the launcher icons are generated by tools/nav-icons.mjs from art that
// lives outside this repo, so nothing in the source tree would notice if one were lost,
// truncated or re-exported in a format the browser will not draw. The failures are quiet
// ones: a missing icon is a broken image in the middle of the tab bar, and an icon left
// out of the service worker's offline set disappears the moment the phone goes offline.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const NAV_DIR = join(ROOT, 'icons', 'nav');

/** The tab ids the shell routes on; the same list tools/nav-icons.mjs generates. */
const NAV = ['home', 'run', 'table', 'library', 'bgm'];
const SIZE = 128;
const PNG_SIGNATURE = [137, 80, 78, 71, 13, 10, 26, 10];

function readPngHeader(buffer) {
  return {
    width: buffer.readUInt32BE(16),
    height: buffer.readUInt32BE(20),
    depth: buffer[24],
    colorType: buffer[25]
  };
}

/**
 * Reads a shipped PNG and checks it is one the browser can draw.
 *
 * Colour type 4, greyscale+alpha, is the one that must not come back: that is the mask
 * format the tab icons used to be, and an `<img>` pointed at a mask draws a white shape on
 * transparency, which on the tab bar is a pale blob rather than an icon. Types 2 and 6
 * (truecolour) would draw correctly — type 3 (palette) is what the tool writes now, for
 * size — so all three are allowed here and the weight is checked separately below.
 */
function readIcon(file, expected) {
  assert.ok(existsSync(file), `${file} is missing — run npm run icons`);
  const buffer = readFileSync(file);
  assert.deepEqual([...buffer.subarray(0, 8)], PNG_SIGNATURE, `${file} is not a PNG`);
  const header = readPngHeader(buffer);
  assert.equal(header.width, expected, `${file} is ${header.width}px wide, expected ${expected}`);
  assert.equal(header.height, expected, `${file} is ${header.height}px tall, expected ${expected}`);
  assert.equal(header.depth, 8, `${file} is ${header.depth}-bit, expected 8`);
  assert.ok([2, 3, 6].includes(header.colorType),
    `${file} has colour type ${header.colorType}; the icons must be colour art, not a mask`);
  return { ...header, bytes: buffer.length };
}

test('every tab icon is present and is colour art', () => {
  for (const name of NAV) {
    readIcon(join(NAV_DIR, `${name}.png`), SIZE);
  }
});

/**
 * The icons are on the critical path of every cold load, and getting this wrong once cost
 * about a megabyte of install-time download for no visible gain: the first truecolour pass
 * produced 43 kB per tab icon against 13 kB for the palette-encoded one. These ceilings are
 * loose — roughly double what the tool writes today — so they fail on a change of technique
 * rather than on a slightly different crop.
 */
test('the icons stay small enough to sit in a cold load', () => {
  const budget = { nav: 26 * 1024, launcher: 260 * 1024 };
  let navTotal = 0;
  for (const name of NAV) {
    const { bytes } = readIcon(join(NAV_DIR, `${name}.png`), SIZE);
    navTotal += bytes;
    assert.ok(bytes <= budget.nav,
      `icons/nav/${name}.png is ${(bytes / 1024).toFixed(1)} kB; the tab icons are loaded on every cold start`);
  }
  assert.ok(navTotal <= budget.nav * 3,
    `the five tab icons total ${(navTotal / 1024).toFixed(1)} kB; they are all in the first screen`);

  const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8'));
  for (const icon of manifest.icons) {
    const { bytes } = readIcon(join(ROOT, icon.src), Number(String(icon.sizes).split('x')[0]));
    assert.ok(bytes <= budget.launcher,
      `${icon.src} is ${(bytes / 1024).toFixed(1)} kB; it is fetched at install time on a phone`);
  }
});

test('the launcher icons exist at the sizes the manifest asks for', () => {
  const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8'));
  const worker = readFileSync(join(ROOT, 'service-worker.js'), 'utf8');

  assert.ok(manifest.icons.length >= 2, 'the manifest lists no icons');
  for (const icon of manifest.icons) {
    const file = join(ROOT, icon.src);
    const size = Number(String(icon.sizes).split('x')[0]);
    const header = readIcon(file, size);
    assert.equal(header.width, header.height, `${icon.src} is not square`);
    // Deliberately absent from OFFLINE_URLS. Nothing in the app draws these — the browser
    // and the OS fetch them at install time, and they are the heaviest files in the
    // project, so precaching them charges every install for something no screen shows.
    assert.doesNotMatch(worker, new RegExp(icon.src.replace(/[.]/g, '\\.')),
      `${icon.src} is in OFFLINE_URLS; the launcher icons are fetched by the manifest at install, not precached`);
  }
});

test('the shell references every tab icon it ships', () => {
  const html = readFileSync(join(ROOT, 'index.html'), 'utf8');
  const worker = readFileSync(join(ROOT, 'service-worker.js'), 'utf8');

  for (const name of NAV) {
    const path = `icons/nav/${name}.png`;
    assert.match(html, new RegExp(path.replace(/[.]/g, '\\.')),
      `${path} is not referenced from index.html, so nothing would draw it`);
    // Not in OFFLINE_URLS means the tab icon 404s the first time the app runs offline,
    // which is a broken image sitting in the tab bar rather than a fallback of any kind.
    assert.match(worker, new RegExp(path.replace(/[.]/g, '\\.')),
      `${path} is missing from OFFLINE_URLS in service-worker.js`);
  }
});
