import { createPfpcClient } from '../pfpc-control.js';
import { state } from '../store.js';
import { companionCharactersForCampaign } from '../companion-rosters.js';
import { actions as loadActions } from '../data.js';
import { esc } from '../dom.js';
import { MAP_WIDTH, MAP_HEIGHT, emptyCampaignMap, sanitizeCampaignMap, hexCenter, nearestVisibleHex, pointerToImagePoint, projectPublicCampaignMap } from '../campaign-map.js';

const MARKERS = { party:'assets/maps/nav-party.png', red:'assets/maps/flag-red.png', yellow:'assets/maps/flag-yellow.png', blue:'assets/maps/flag-blue.png', enemy:'assets/maps/marker-enemy.svg' };
const colors=['red','yellow','blue'];
const escText=value=>esc(String(value??''));
export function explorationMarkup({campaignId,characters,workflow,activityOptions,map,revision,status}) {
  const records=new Map((workflow?.characters||[]).map(row=>[row.characterId,row]));
  const activity=characters.map(ch=>{const w=records.get(ch.id);const selected=w?.exploration?.activityId||'';const choice=activityOptions.find(a=>a.id===selected);const selectedName=choice?.name||w?.exploration?.activityName||'';return `<article class="gm-exploration-character"><details><summary><span><b>${escText(ch.name)}</b><small>${escText(w?.playerName||w?.displayName||ch.playerName||'Player not set')}</small></span><strong class="${selected?'':'missing'}">${selected?escText(selectedName||'Selected activity'): 'No activity selected'}</strong></summary><div class="gm-activity-control"><label>Activity <select data-activity="${escText(ch.id)}"><option value="">No activity</option>${activityOptions.map(a=>`<option value="${escText(a.id)}" ${a.id===selected?'selected':''}>${escText(a.name)}</option>`).join('')}</select></label>${selected?`<p>${escText(choice?.notes||choice?.description||w?.exploration?.description||'No description available.')}</p>`:''}</div></details></article>`;}).join('');
  const marker=(key,hex,visible=true)=>{if(!hex)return '';const p=hexCenter(parseHex(hex));return `<img class="gm-map-marker ${visible?'':'hidden-marker'}" src="${MARKERS[key]||MARKERS.enemy}" alt="${escText(key)}${visible?'':' hidden'}" style="left:${p.x/MAP_WIDTH*100}%;top:${p.y/MAP_HEIGHT*100}%">`;};
  const markers=[marker('party',map.party),...colors.map(c=>marker(c,map.flags[c].hex,map.flags[c].visible)),...map.enemies.map(e=>marker('enemy',e.hex,e.visible)),...(map.factions||[]).map(f=>marker('enemy',f.hex,f.visible))].join('');
  return `<section class="gm-exploration" data-campaign="${escText(campaignId)}"><header><h2>Exploration</h2><label>Campaign <select data-campaign>${Object.keys(state.companion.assignments||{}).map(id=>`<option ${id===campaignId?'selected':''}>${escText(id)}</option>`).join('')}</select></label></header><p class="gm-sync" role="status">${escText(status||'Connected state loaded')}</p><div class="gm-activity-list">${characters.length?activity:'<p class="empty">No active player characters linked to this campaign.</p>'}</div><section class="gm-map-card"><div class="gm-map-heading"><h3>Maguuma Jungle</h3><p>Players see solid markers. Faded markers are GM only.</p></div><div class="gm-map" data-map><img class="gm-map-art" src="assets/maps/maguuma-jungle-hex-map.png" alt="Maguuma Jungle hex map" width="${MAP_WIDTH}" height="${MAP_HEIGHT}">${markers}<button class="gm-map-capture" type="button" data-place-map aria-label="Place selected marker on map"></button></div><div class="gm-map-tools"><label>Marker <select data-marker><option value="party">Party</option>${colors.map(c=>`<option value="${c}">${c[0].toUpperCase()+c.slice(1)} flag</option>`).join('')}<option value="enemy">New enemy</option>${(map.enemies||[]).map((e,i)=>`<option value="${escText(e.id)}">Enemy ${i+1}</option>`).join('')}<option value="faction:royal-guard">Royal Guard</option><option value="faction:alliance">Alliance</option></select></label><button type="button" data-arm>Place / move</button><button type="button" data-clear>Clear selected</button></div><div class="gm-map-tools gm-map-keyboard"><label>Hex q <input type="number" data-hex-q min="0" step="1" value="0"></label><label>r <input type="number" data-hex-r min="0" step="1" value="0"></label><button type="button" data-place-hex>Place at hex</button></div><div class="gm-map-state"><strong>Player view</strong><span>${projectPublicCampaignMap(map).party?'Party placed':'Party not placed'} · ${projectPublicCampaignMap(map).flags.length} flags · ${projectPublicCampaignMap(map).enemies.length} enemies visible</span></div><div class="gm-map-visibility">${colors.map(c=>`<label><input type="checkbox" data-visibility="${c}" ${map.flags[c].visible?'checked':''}> ${c} flag visible</label>`).join('')}${map.enemies.map((e,i)=>`<label><input type="checkbox" data-enemy-visibility="${escText(e.id)}" ${e.visible?'checked':''}> Enemy ${i+1} visible</label>`).join('')}${(map.factions||[]).map(f=>`<label><input type="checkbox" data-faction-visibility="${escText(f.kind)}" ${f.visible?'checked':''}> ${escText(f.kind)} visible</label>`).join('')}</div><p class="gm-map-revision" data-revision="${revision}">Map revision ${revision}</p></section></section>`;
}

// Keep the exact canonical parser semantics centralized in campaign-map.js.
import { parseHexId } from '../campaign-map.js';
function parseHex(value){return parseHexId(value);}

export function bindExploration(root,{client=createPfpcClient(),actions=loadActions,campaignId=()=>Object.keys(state.companion.assignments||{})[0]||'',notify=()=>{}}={}) {
  let currentCampaign='', workflow=null, map=emptyCampaignMap(), mapRevision=0, busy=false, placing=false, actionRows=[];
  const draw=(status='Connected state loaded')=>{if(!currentCampaign){root.innerHTML='<section class="gm-exploration"><h2>Exploration</h2><p class="empty">Link player characters to a campaign in Party.</p></section>';return;}root.innerHTML=explorationMarkup({campaignId:currentCampaign,characters:companionCharactersForCampaign(state.companion,currentCampaign),workflow,activityOptions:actionRows.filter(a=>a.traits?.includes('Exploration')),map,revision:mapRevision,status});};
  async function refresh(id=currentCampaign){currentCampaign=id;if(!id){draw();return;}busy=true;draw('Loading campaign…');const [w,m,a]=await Promise.all([client.getWorkflow(id,{retries:1}),client.getCampaignMap(id,{retries:1}),actions()]);actionRows=a||[];if(w.state==='ok'){workflow=w.data.workflow||w.data; }if(m.state==='ok'){const envelope=m.data;map=sanitizeCampaignMap(envelope.map||envelope);mapRevision=envelope.revision||0;}else if(m.state==='unreachable'||m.state==='conflict'){draw(`Map unavailable: ${m.state}`);busy=false;return;}busy=false;draw(w.state==='ok'?'Connected state loaded':`Activities unavailable: ${w.state}`);}
  root.addEventListener('change',async e=>{const t=e.target;if(t.matches('[data-campaign]')){await refresh(t.value);return;}if(t.matches('[data-activity]')){busy=true;const result=await client.setExploration(currentCampaign,workflow.revision,t.dataset.activity,t.value||null);if(result.state==='ok'){workflow=result.data.workflow||result.data;draw();}else if(result.state==='conflict'){await refresh();notify('Activity changed elsewhere. Latest state loaded.');}else draw(`Activity update failed: ${result.state}`);busy=false;return;}if(t.matches('[data-visibility]')){map.flags[t.dataset.visibility].visible=t.checked;await saveMap();return;}if(t.matches('[data-enemy-visibility]')){const enemy=map.enemies.find(x=>x.id===t.dataset.enemyVisibility);if(enemy){enemy.visible=t.checked;await saveMap();}}if(t.matches('[data-faction-visibility]')){const faction=map.factions?.find(x=>x.kind===t.dataset.factionVisibility);if(faction){faction.visible=t.checked;await saveMap();}}});
  async function saveMap(){if(busy)return;busy=true;const result=await client.setCampaignMap(currentCampaign,mapRevision,map);if(result.state==='ok'){const envelope=result.data;map=sanitizeCampaignMap(envelope.map||envelope);mapRevision=envelope.revision??mapRevision+1;draw();}else if(result.state==='conflict'){await refresh();notify('Map changed elsewhere. Latest state loaded.');}else{await refresh();draw(`Map update failed: ${result.state}`);}busy=false;}
  async function place(hexId){const hex=parseHexId(hexId);if(!hex||busy){notify('Choose a valid visible hex.');return;}const key=root.querySelector('[data-marker]').value;if(key==='party')map.party=hex.id;else if(colors.includes(key))map.flags[key].hex=hex.id;else if(key.startsWith('enemy-')){const enemy=map.enemies.find(x=>x.id===key);if(enemy)enemy.hex=hex.id;}else if(key.startsWith('faction:')){const kind=key.slice(8);map.factions=map.factions||[];const faction=map.factions.find(x=>x.kind===kind);if(faction)faction.hex=hex.id;else map.factions.push({kind,hex:hex.id,visible:false});}else{let id,seq=0;do{id=`enemy-${Date.now().toString(36)}${seq++||''}`;}while(map.enemies.some(enemy=>enemy.id===id));map.enemies.push({id,hex:hex.id,visible:false});}placing=false;await saveMap();}
  root.addEventListener('click',async e=>{const t=e.target;if(t.matches('[data-arm]')){placing=true;root.querySelector('[data-place-map]')?.focus();return;}if(t.matches('[data-place-map]')){if(!placing||busy)return;const rect=t.parentElement.getBoundingClientRect(),p=pointerToImagePoint(e.clientX,e.clientY,rect),hex=p&&nearestVisibleHex(p);if(!hex){notify('Choose a visible hex.');return;}await place(hex.id);return;}if(t.matches('[data-place-hex]')){await place(`h2:${root.querySelector('[data-hex-q]').value}:${root.querySelector('[data-hex-r]').value}`);return;}if(t.matches('[data-clear]')){const key=root.querySelector('[data-marker]').value;if(key==='party')map.party=null;else if(colors.includes(key))map.flags[key].hex=null;else if(key.startsWith('enemy-'))map.enemies=map.enemies.filter(x=>x.id!==key);else if(key.startsWith('faction:'))map.factions=(map.factions||[]).filter(x=>x.kind!==key.slice(8));await saveMap();}});
  root.innerHTML='<section class="gm-exploration"><h2>Exploration</h2><p>Loading…</p></section>';void actions().then(a=>{actionRows=a||[];return refresh(campaignId());});
}
