// Lazy, cached loaders for the bundled data files.
//
// The reference files total ~10 MB across sixteen categories, so nothing is fetched
// until a screen actually asks for it. Each file is fetched at most once per session;
// the service worker caches it on first use for offline runs.
//
// data/index.json is the manifest the Library screen reads to build its category list,
// so adding a category to tools/fetch-aon.mjs needs no view change. data/campaign.json
// is hand-authored and is not part of the manifest.

const cache = new Map();

/**
 * Fetch and parse `data/<file>` once. Resolves to null if the file is missing or
 * malformed — a screen with no data still renders, it just says so.
 */
function json(file) {
  if (!cache.has(file)) {
    cache.set(file, fetch(`data/${file}`)
      .then(r => {
        if (!r.ok) throw new Error(`${r.status} ${r.statusText}`);
        return r.json();
      })
      .catch(err => {
        console.warn(`Could not load ${file}`, err);
        cache.delete(file);   // let a later screen retry
        return null;
      }));
  }
  return cache.get(file);
}

/** The Library's category list: [{ name, file, key, label, glyph, blurb, count }]. */
export function manifest() {
  return json('index.json').then(j => j?.categories || []);
}

/** The records for one manifest category. */
export function records(category) {
  return json(category.file).then(j => j?.[category.key] || []);
}

/** The committed player-character roster: { groups, characters }, or null. */
export function characters() {
  return json('characters.json');
}

/**
 * Full rules text for what the campaign's characters use: feats, class features, carried
 * items, spells and formulas, plus each prepared caster's selectable spell list.
 * Generated by tools/fetch-codex.mjs; ~0.9 MB, so it loads only when a sheet asks.
 */
export function codex() {
  return json('codex.json');
}

/** Hand-authored campaign notes, or null if absent. */
export function campaign() {
  return json('campaign.json');
}

/** Hand-authored BGM links, kept separate from the campaign notes. */
export function soundtrack() {
  return json('soundtrack.json').then(j => j?.tracks || []);
}

/**
 * Conditions with their summaries, for the combat tracker's chips. 17 KB, and the
 * tracker is the one screen a GM leaves open, so it loads with the view.
 */
export function conditions() {
  return json('conditions.json').then(j => j?.conditions || []);
}

/**
 * Traits with the groups AoN files them under — "Creature Type", "Rarity", "Weapon" and
 * so on. 0.16 MB, and the encounter planner's filter dropdowns are built from it.
 */
export function traits() {
  return json('traits.json').then(j => j?.traits || []);
}

/**
 * Every priced item, for the loot suggester. 3.0 MB, so it loads only when the Loot
 * screen asks for a selection; the service worker keeps it after the first use.
 */
export function equipment() {
  return json('equipment.json').then(j => j?.items || []);
}

/** Creatures, used by the encounter planner's quick-add sheet. */
export function creatures() {
  return json('creatures.json').then(j => j?.creatures || []);
}
